import { EContactStatus, EStatus, EUserStatus } from "./enum";

// User mock data
export const users: IUser[] = [
    {
        id: "user1",
        email: "alice@example.com",
        password: "password123",
        name: "Alice Nguyen",
        phone: "0901234567",
        role: "admin",
        status: EUserStatus.PENDING,
    },
    {
        id: "user2",
        email: "bob@example.com",
        password: "password456",
        name: "Bob Tran",
        phone: "0902345678",
        role: "user",
        status: EUserStatus.PENDING,
    },
    {
        id: "user3",
        email: "charlie@example.com",
        password: "password789",
        name: "Charlie Le",
        phone: "0903456789",
        role: "user",
        status: EUserStatus.PENDING,
    },
    {
        id: "user4",
        email: "diana@example.com",
        password: "password101",
        name: "Diana Pham",
        phone: "0904567890",
        role: "editor",
        status: EUserStatus.PENDING,
    },
    {
        id: "user5",
        email: "edward@example.com",
        password: "password202",
        name: "Edward Vo",
        phone: "0905678901",
        role: "user",
        status: EUserStatus.PENDING,
    },
    {
        id: "user6",
        email: "fiona@example.com",
        password: "password303",
        name: "Fiona Dang",
        phone: "0906789012",
        role: "user",
        status: EUserStatus.PENDING,
    },
    {
        id: "user7",
        email: "george@example.com",
        password: "password404",
        name: "George Bui",
        phone: "0907890123",
        role: "user",
        status: EUserStatus.PENDING,
    },
    {
        id: "user8",
        email: "hannah@example.com",
        password: "password505",
        name: "Hannah Ho",
        phone: "0908901234",
        role: "user",
        status: EUserStatus.PENDING,
    },
    {
        id: "user9",
        email: "ian@example.com",
        password: "password606",
        name: "Ian Nguyen",
        phone: "0909012345",
        role: "user",
        status: EUserStatus.PENDING,
    },
    {
        id: "user10",
        email: "julia@example.com",
        password: "password707",
        name: "Julia Phan",
        phone: "0910123456",
        role: "user",
        status: EUserStatus.PENDING,
    },
];

// Program mock data
export const programs: IProgram[] = [
    {
        id: "program1",
        title: "Du học Úc",
        description: "Chương trình du học tại Úc với nhiều ưu đãi.",
        country: "Australia",
        duration: "2 năm",
        tuition: "$20,000",
        requirements: ["IELTS 6.0", "Tốt nghiệp THPT"],
        benefits: ["Cơ hội việc làm", "Định cư"],
        imageUrl: "/images/programs/australia.jpg",
        featured: true,
        createdAt: new Date("2025-01-01"),
        updatedAt: new Date("2025-06-01"),
        status: EStatus.ACTIVE,
    },
    {
        id: "program2",
        title: "Du học Canada",
        description: "Chương trình du học tại Canada.",
        country: "Canada",
        duration: "3 năm",
        tuition: "$25,000",
        requirements: ["IELTS 6.5", "Tốt nghiệp THPT"],
        benefits: ["Cơ hội việc làm", "Học bổng"],
        imageUrl: "/images/programs/canada.jpg",
        featured: false,
        createdAt: new Date("2025-02-01"),
        updatedAt: new Date("2025-06-02"),
        status: EStatus.ACTIVE,
    },
    {
        id: "program3",
        title: "Du học Đức",
        description: "Chương trình du học tại Đức.",
        country: "Germany",
        duration: "2 năm",
        tuition: "$18,000",
        requirements: ["B1 tiếng Đức", "Tốt nghiệp THPT"],
        benefits: ["Miễn học phí", "Cơ hội việc làm"],
        imageUrl: "/images/programs/germany.jpg",
        featured: true,
        createdAt: new Date("2025-03-01"),
        updatedAt: new Date("2025-06-03"),
        status: EStatus.ACTIVE,
    },
    {
        id: "program4",
        title: "Du học Nhật Bản",
        description: "Chương trình du học tại Nhật Bản.",
        country: "Japan",
        duration: "1 năm",
        tuition: "$15,000",
        requirements: ["N3 tiếng Nhật", "Tốt nghiệp THPT"],
        benefits: ["Cơ hội việc làm", "Học bổng"],
        imageUrl: "/images/programs/japan.jpg",
        featured: false,
        createdAt: new Date("2025-04-01"),
        updatedAt: new Date("2025-06-04"),
        status: EStatus.ACTIVE,
    },
    {
        id: "program5",
        title: "Du học Hàn Quốc",
        description: "Chương trình du học tại Hàn Quốc.",
        country: "South Korea",
        duration: "2 năm",
        tuition: "$17,000",
        requirements: ["TOPIK 3", "Tốt nghiệp THPT"],
        benefits: ["Cơ hội việc làm", "Định cư"],
        imageUrl: "/images/programs/korea.jpg",
        featured: true,
        createdAt: new Date("2025-05-01"),
        updatedAt: new Date("2025-06-05"),
        status: EStatus.ACTIVE,
    },
    {
        id: "program6",
        title: "Du học Đài Loan",
        description: "Chương trình du học tại Đài Loan.",
        country: "Taiwan",
        duration: "1.5 năm",
        tuition: "$16,000",
        requirements: ["TOCFL 3", "Tốt nghiệp THPT"],
        benefits: ["Cơ hội việc làm", "Học bổng"],
        imageUrl: "/images/programs/taiwan.jpg",
        featured: false,
        createdAt: new Date("2025-06-01"),
        updatedAt: new Date("2025-06-06"),
        status: EStatus.ACTIVE,
    },
    {
        id: "program7",
        title: "Du học Mỹ",
        description: "Chương trình du học tại Mỹ.",
        country: "USA",
        duration: "4 năm",
        tuition: "$30,000",
        requirements: ["SAT", "Tốt nghiệp THPT"],
        benefits: ["Cơ hội việc làm", "Học bổng"],
        imageUrl: "/images/programs/usa.jpg",
        featured: true,
        createdAt: new Date("2025-07-01"),
        updatedAt: new Date("2025-07-07"),
        status: EStatus.ACTIVE,
    },
    {
        id: "program8",
        title: "Du học Pháp",
        description: "Chương trình du học tại Pháp.",
        country: "France",
        duration: "3 năm",
        tuition: "$22,000",
        requirements: ["B2 tiếng Pháp", "Tốt nghiệp THPT"],
        benefits: ["Cơ hội việc làm", "Học bổng"],
        imageUrl: "/images/programs/france.jpg",
        featured: false,
        createdAt: new Date("2025-08-01"),
        updatedAt: new Date("2025-08-08"),
        status: EStatus.ACTIVE,
    },
    {
        id: "program9",
        title: "Du học Singapore",
        description: "Chương trình du học tại Singapore.",
        country: "Singapore",
        duration: "2 năm",
        tuition: "$19,000",
        requirements: ["IELTS 6.0", "Tốt nghiệp THPT"],
        benefits: ["Cơ hội việc làm", "Học bổng"],
        imageUrl: "/images/programs/singapore.jpg",
        featured: true,
        createdAt: new Date("2025-09-01"),
        updatedAt: new Date("2025-09-09"),
        status: EStatus.ACTIVE,
    },
    {
        id: "program10",
        title: "Du học Thụy Sĩ",
        description: "Chương trình du học tại Thụy Sĩ.",
        country: "Switzerland",
        duration: "2 năm",
        tuition: "$21,000",
        requirements: ["B2 tiếng Anh", "Tốt nghiệp THPT"],
        benefits: ["Cơ hội việc làm", "Học bổng"],
        imageUrl: "/images/programs/switzerland.jpg",
        featured: false,
        createdAt: new Date("2025-10-01"),
        updatedAt: new Date("2025-10-10"),
        status: EStatus.ACTIVE,
    },
];

// Blog mock data
export const blogs: IBlog[] = [
    {
        id: "blog1",
        title: "Kinh nghiệm du học Úc",
        excerpt: "Chia sẻ kinh nghiệm du học Úc.",
        content: "Nội dung chi tiết về kinh nghiệm du học Úc...",
        author: users[0].name,
        publishedAt: "2025-01-10",
        imageUrl: "/images/blogs/australia.jpg",
        category: "Kinh nghiệm",
        slug: "kinh-nghiem-du-hoc-uc",
        status: EStatus.ACTIVE,
    },
    {
        id: "blog2",
        title: "Học bổng du học Canada",
        excerpt: "Thông tin học bổng du học Canada.",
        content: "Nội dung chi tiết về học bổng du học Canada...",
        author: users[1].name,
        publishedAt: "2025-02-15",
        imageUrl: "/images/blogs/canada.jpg",
        category: "Học bổng",
        slug: "hoc-bong-du-hoc-canada",
        status: EStatus.ACTIVE,
    },
    {
        id: "blog3",
        title: "Du học Đức miễn học phí",
        excerpt: "Du học Đức không mất học phí.",
        content: "Nội dung chi tiết về du học Đức miễn học phí...",
        author: users[2].name,
        publishedAt: "2025-03-20",
        imageUrl: "/images/blogs/germany.jpg",
        category: "Thông tin",
        slug: "du-hoc-duc-mien-hoc-phi",
        status: EStatus.ACTIVE,
    },
    {
        id: "blog4",
        title: "Cơ hội việc làm tại Nhật Bản",
        excerpt: "Việc làm sau khi du học Nhật Bản.",
        content: "Nội dung chi tiết về việc làm tại Nhật Bản...",
        author: users[3].name,
        publishedAt: "2025-04-25",
        imageUrl: "/images/blogs/japan.jpg",
        category: "Việc làm",
        slug: "co-hoi-viec-lam-nhat-ban",
        status: EStatus.ACTIVE,
    },
    {
        id: "blog5",
        title: "Du học Hàn Quốc và định cư",
        excerpt: "Cơ hội định cư sau du học Hàn Quốc.",
        content: "Nội dung chi tiết về định cư Hàn Quốc...",
        author: users[4].name,
        publishedAt: "2025-05-30",
        imageUrl: "/images/blogs/korea.jpg",
        category: "Định cư",
        slug: "du-hoc-han-quoc-va-dinh-cu",
        status: EStatus.ACTIVE,
    },
    {
        id: "blog6",
        title: "Du học Đài Loan dễ dàng",
        excerpt: "Các bước du học Đài Loan.",
        content: "Nội dung chi tiết về du học Đài Loan...",
        author: users[5].name,
        publishedAt: "2025-06-05",
        imageUrl: "/images/blogs/taiwan.jpg",
        category: "Thông tin",
        slug: "du-hoc-dai-loan-de-dang",
        status: EStatus.ACTIVE,
    },
    {
        id: "blog7",
        title: "Du học Mỹ cần chuẩn bị gì?",
        excerpt: "Chuẩn bị du học Mỹ.",
        content: "Nội dung chi tiết về chuẩn bị du học Mỹ...",
        author: users[6].name,
        publishedAt: "2025-07-10",
        imageUrl: "/images/blogs/usa.jpg",
        category: "Chuẩn bị",
        slug: "du-hoc-my-can-chuan-bi-gi",
        status: EStatus.ACTIVE,
    },
    {
        id: "blog8",
        title: "Du học Pháp và học bổng",
        excerpt: "Học bổng du học Pháp.",
        content: "Nội dung chi tiết về học bổng Pháp...",
        author: users[7].name,
        publishedAt: "2025-08-15",
        imageUrl: "/images/blogs/france.jpg",
        category: "Học bổng",
        slug: "du-hoc-phap-va-hoc-bong",
        status: EStatus.ACTIVE,
    },
    {
        id: "blog9",
        title: "Du học Singapore và cơ hội việc làm",
        excerpt: "Việc làm sau du học Singapore.",
        content: "Nội dung chi tiết về việc làm Singapore...",
        author: users[8].name,
        publishedAt: "2025-09-20",
        imageUrl: "/images/blogs/singapore.jpg",
        category: "Việc làm",
        slug: "du-hoc-singapore-va-co-hoi-viec-lam",
        status: EStatus.ACTIVE,
    },
    {
        id: "blog10",
        title: "Du học Thụy Sĩ và trải nghiệm",
        excerpt: "Trải nghiệm du học Thụy Sĩ.",
        content: "Nội dung chi tiết về trải nghiệm Thụy Sĩ...",
        author: users[9].name,
        publishedAt: "2025-10-25",
        imageUrl: "/images/blogs/switzerland.jpg",
        category: "Trải nghiệm",
        slug: "du-hoc-thuy-si-va-trai-nghiem",
        status: EStatus.ACTIVE,
    },
];

// Job mock data
export const jobs: IJob[] = [
    {
        id: "job1",
        title: "Nhân viên văn phòng Úc",
        country: "Australia",
        imageUrl: "/images/jobs/australia.jpg",
        positions: 5,
        location: "Sydney",
        salary: "$3,000/month",
        applicationDeadline: "2025-02-01",
        estimatedDeparture: "2025-03-01",
        requirements: ["Tiếng Anh tốt", "Kinh nghiệm văn phòng"],
        benefits: ["Bảo hiểm", "Thưởng"],
        description: "Công việc văn phòng tại Úc.",
        company: "AUS Office",
        workType: "Full-time",
        featured: true,
        workingHours: "40h/tuần",
        overtime: "Có",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Văn phòng hiện đại",
        trainingPeriod: "1 tháng",
        status: EStatus.ACTIVE,
    },
    {
        id: "job2",
        title: "Nhân viên nhà hàng Canada",
        country: "Canada",
        imageUrl: "/images/jobs/canada.jpg",
        positions: 3,
        location: "Toronto",
        salary: "$2,800/month",
        applicationDeadline: "2025-03-01",
        estimatedDeparture: "2025-04-01",
        requirements: ["Tiếng Anh cơ bản", "Kinh nghiệm nhà hàng"],
        benefits: ["Bảo hiểm", "Ăn trưa miễn phí"],
        description: "Công việc nhà hàng tại Canada.",
        company: "CAN Restaurant",
        workType: "Part-time",
        featured: false,
        workingHours: "30h/tuần",
        overtime: "Không",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Nhà hàng sang trọng",
        trainingPeriod: "2 tuần",
        status: EStatus.ACTIVE,
    },
    {
        id: "job3",
        title: "Kỹ sư Đức",
        country: "Germany",
        imageUrl: "/images/jobs/germany.jpg",
        positions: 2,
        location: "Berlin",
        salary: "$4,000/month",
        applicationDeadline: "2025-04-01",
        estimatedDeparture: "2025-05-01",
        requirements: ["Tiếng Đức B1", "Bằng kỹ sư"],
        benefits: ["Bảo hiểm", "Thưởng"],
        description: "Công việc kỹ sư tại Đức.",
        company: "GER Engineering",
        workType: "Full-time",
        featured: true,
        workingHours: "40h/tuần",
        overtime: "Có",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Xưởng hiện đại",
        trainingPeriod: "2 tháng",
        status: EStatus.ACTIVE,
    },
    {
        id: "job4",
        title: "Nhân viên khách sạn Nhật Bản",
        country: "Japan",
        imageUrl: "/images/jobs/japan.jpg",
        positions: 4,
        location: "Tokyo",
        salary: "$2,500/month",
        applicationDeadline: "2025-05-01",
        estimatedDeparture: "2025-06-01",
        requirements: ["Tiếng Nhật N3", "Kinh nghiệm khách sạn"],
        benefits: ["Bảo hiểm", "Ăn trưa miễn phí"],
        description: "Công việc khách sạn tại Nhật Bản.",
        company: "JPN Hotel",
        workType: "Full-time",
        featured: false,
        workingHours: "40h/tuần",
        overtime: "Có",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Khách sạn 5 sao",
        trainingPeriod: "1 tháng",
        status: EStatus.ACTIVE,
    },
    {
        id: "job5",
        title: "Nhân viên sản xuất Hàn Quốc",
        country: "South Korea",
        imageUrl: "/images/jobs/korea.jpg",
        positions: 6,
        location: "Seoul",
        salary: "$2,700/month",
        applicationDeadline: "2025-06-01",
        estimatedDeparture: "2025-07-01",
        requirements: ["Tiếng Hàn TOPIK 3", "Kinh nghiệm sản xuất"],
        benefits: ["Bảo hiểm", "Thưởng"],
        description: "Công việc sản xuất tại Hàn Quốc.",
        company: "KOR Factory",
        workType: "Full-time",
        featured: true,
        workingHours: "40h/tuần",
        overtime: "Có",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Nhà máy hiện đại",
        trainingPeriod: "2 tháng",
        status: EStatus.ACTIVE,
    },
    {
        id: "job6",
        title: "Nhân viên văn phòng Đài Loan",
        country: "Taiwan",
        imageUrl: "/images/jobs/taiwan.jpg",
        positions: 2,
        location: "Taipei",
        salary: "$2,600/month",
        applicationDeadline: "2025-07-01",
        estimatedDeparture: "2025-08-01",
        requirements: ["Tiếng Trung TOCFL 3", "Kinh nghiệm văn phòng"],
        benefits: ["Bảo hiểm", "Thưởng"],
        description: "Công việc văn phòng tại Đài Loan.",
        company: "TWN Office",
        workType: "Part-time",
        featured: false,
        workingHours: "30h/tuần",
        overtime: "Không",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Văn phòng hiện đại",
        trainingPeriod: "1 tháng",
        status: EStatus.ACTIVE,
    },
    {
        id: "job7",
        title: "Nhân viên nhà hàng Mỹ",
        country: "USA",
        imageUrl: "/images/jobs/usa.jpg",
        positions: 3,
        location: "New York",
        salary: "$3,200/month",
        applicationDeadline: "2025-08-01",
        estimatedDeparture: "2025-09-01",
        requirements: ["Tiếng Anh tốt", "Kinh nghiệm nhà hàng"],
        benefits: ["Bảo hiểm", "Ăn trưa miễn phí"],
        description: "Công việc nhà hàng tại Mỹ.",
        company: "USA Restaurant",
        workType: "Full-time",
        featured: true,
        workingHours: "40h/tuần",
        overtime: "Có",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Nhà hàng sang trọng",
        trainingPeriod: "2 tuần",
        status: EStatus.ACTIVE,
    },
    {
        id: "job8",
        title: "Nhân viên khách sạn Pháp",
        country: "France",
        imageUrl: "/images/jobs/france.jpg",
        positions: 2,
        location: "Paris",
        salary: "$2,900/month",
        applicationDeadline: "2025-09-01",
        estimatedDeparture: "2025-10-01",
        requirements: ["Tiếng Pháp B2", "Kinh nghiệm khách sạn"],
        benefits: ["Bảo hiểm", "Ăn trưa miễn phí"],
        description: "Công việc khách sạn tại Pháp.",
        company: "FRA Hotel",
        workType: "Full-time",
        featured: false,
        workingHours: "40h/tuần",
        overtime: "Có",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Khách sạn 5 sao",
        trainingPeriod: "1 tháng",
        status: EStatus.ACTIVE,
    },
    {
        id: "job9",
        title: "Nhân viên sản xuất Singapore",
        country: "Singapore",
        imageUrl: "/images/jobs/singapore.jpg",
        positions: 4,
        location: "Singapore",
        salary: "$2,800/month",
        applicationDeadline: "2025-10-01",
        estimatedDeparture: "2025-11-01",
        requirements: ["Tiếng Anh tốt", "Kinh nghiệm sản xuất"],
        benefits: ["Bảo hiểm", "Thưởng"],
        description: "Công việc sản xuất tại Singapore.",
        company: "SG Factory",
        workType: "Full-time",
        featured: true,
        workingHours: "40h/tuần",
        overtime: "Có",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Nhà máy hiện đại",
        trainingPeriod: "2 tháng",
        status: EStatus.ACTIVE,
    },
    {
        id: "job10",
        title: "Nhân viên văn phòng Thụy Sĩ",
        country: "Switzerland",
        imageUrl: "/images/jobs/switzerland.jpg",
        positions: 2,
        location: "Zurich",
        salary: "$3,100/month",
        applicationDeadline: "2025-11-01",
        estimatedDeparture: "2025-12-01",
        requirements: ["Tiếng Anh B2", "Kinh nghiệm văn phòng"],
        benefits: ["Bảo hiểm", "Thưởng"],
        description: "Công việc văn phòng tại Thụy Sĩ.",
        company: "SUI Office",
        workType: "Full-time",
        featured: false,
        workingHours: "40h/tuần",
        overtime: "Có",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Văn phòng hiện đại",
        trainingPeriod: "1 tháng",
        status: EStatus.ACTIVE,
    },
];

// Contact mock data
export const contacts: IContact[] = [
    {
        id: "contact1",
        name: "Nguyen Van A",
        email: "nva@example.com",
        phone: "0912345678",
        program: programs[0],
        message: "Tôi muốn biết thêm về chương trình Úc.",
        resolvedBy: users[0].name,
        resolvedAt: "2025-01-15",
        createdAt: "2025-01-10",
        updatedAt: "2025-01-15",
        status: EContactStatus.RESOLVED,
    },
    {
        id: "contact2",
        name: "Tran Thi B",
        email: "ttb@example.com",
        phone: "0923456789",
        program: programs[1],
        message: "Tôi muốn đăng ký chương trình Canada.",
        resolvedBy: users[1].name,
        resolvedAt: "2025-02-20",
        createdAt: "2025-02-15",
        updatedAt: "2025-02-20",
        status: EContactStatus.RESOLVED,
    },
    {
        id: "contact3",
        name: "Le Van C",
        email: "lvc@example.com",
        phone: "0934567890",
        program: programs[2],
        message: "Tôi cần tư vấn về du học Đức.",
        resolvedBy: users[2].name,
        resolvedAt: "2025-03-25",
        createdAt: "2025-03-20",
        updatedAt: "2025-03-25",
        status: EContactStatus.RESOLVED,
    },
    {
        id: "contact4",
        name: "Pham Thi D",
        email: "ptd@example.com",
        phone: "0945678901",
        program: programs[3],
        message: "Tôi muốn hỏi về chương trình Nhật Bản.",
        resolvedBy: users[3].name,
        resolvedAt: "2025-04-30",
        createdAt: "2025-04-25",
        updatedAt: "2025-04-30",
        status: EContactStatus.RESOLVED,
    },
    {
        id: "contact5",
        name: "Vo Van E",
        email: "vve@example.com",
        phone: "0956789012",
        program: programs[4],
        message: "Tôi muốn biết về du học Hàn Quốc.",
        resolvedBy: users[4].name,
        resolvedAt: "2025-05-05",
        createdAt: "2025-05-01",
        updatedAt: "2025-05-05",
        status: EContactStatus.RESOLVED,
    },
    {
        id: "contact6",
        name: "Dang Thi F",
        email: "dtf@example.com",
        phone: "0967890123",
        program: programs[5],
        message: "Tôi muốn hỏi về chương trình Đài Loan.",
        resolvedBy: users[5].name,
        resolvedAt: "2025-06-10",
        createdAt: "2025-06-05",
        updatedAt: "2025-06-10",
        status: EContactStatus.RESOLVED,
    },
    {
        id: "contact7",
        name: "Bui Van G",
        email: "bvg@example.com",
        phone: "0978901234",
        program: programs[6],
        message: "Tôi muốn đăng ký chương trình Mỹ.",
        resolvedBy: users[6].name,
        resolvedAt: "2025-07-15",
        createdAt: "2025-07-10",
        updatedAt: "2025-07-15",
        status: EContactStatus.RESOLVED,
    },
    {
        id: "contact8",
        name: "Ho Thi H",
        email: "hth@example.com",
        phone: "0989012345",
        program: programs[7],
        message: "Tôi muốn hỏi về chương trình Pháp.",
        resolvedBy: users[7].name,
        resolvedAt: "2025-08-20",
        createdAt: "2025-08-15",
        updatedAt: "2025-08-20",
        status: EContactStatus.RESOLVED,
    },
    {
        id: "contact9",
        name: "Nguyen Van I",
        email: "nvi@example.com",
        phone: "0990123456",
        program: programs[8],
        message: "Tôi muốn biết về du học Singapore.",
        resolvedBy: users[8].name,
        resolvedAt: "2025-09-25",
        createdAt: "2025-09-20",
        updatedAt: "2025-09-25",
        status: EContactStatus.RESOLVED,
    },
    {
        id: "contact10",
        name: "Phan Thi J",
        email: "ptj@example.com",
        phone: "0911234567",
        program: programs[9],
        message: "Tôi muốn hỏi về chương trình Thụy Sĩ.",
        resolvedBy: users[9].name,
        resolvedAt: "2025-10-30",
        createdAt: "2025-10-25",
        updatedAt: "2025-10-30",
        status: EContactStatus.RESOLVED,
    },
];

// FAQ mock data
export const faqs: IFAQ[] = [
    {
        id: "faq1",
        question: "Điều kiện du học Úc là gì?",
        answer: "Cần IELTS 6.0 và tốt nghiệp THPT.",
        category: "Úc",
        status: EStatus.ACTIVE,
    },
    {
        id: "faq2",
        question: "Học phí du học Canada bao nhiêu?",
        answer: "Khoảng $25,000/năm.",
        category: "Canada",
        status: EStatus.ACTIVE,
    },
    {
        id: "faq3",
        question: "Du học Đức có miễn học phí không?",
        answer: "Có, nhiều trường miễn học phí.",
        category: "Đức",
        status: EStatus.ACTIVE,
    },
    {
        id: "faq4",
        question: "Cần chứng chỉ gì để du học Nhật Bản?",
        answer: "Cần N3 tiếng Nhật.",
        category: "Nhật Bản",
        status: EStatus.ACTIVE,
    },
    {
        id: "faq5",
        question: "Cơ hội việc làm sau du học Hàn Quốc?",
        answer: "Nhiều cơ hội việc làm và định cư.",
        category: "Hàn Quốc",
        status: EStatus.ACTIVE,
    },
    {
        id: "faq6",
        question: "Du học Đài Loan cần chứng chỉ gì?",
        answer: "Cần TOCFL 3.",
        category: "Đài Loan",
        status: EStatus.ACTIVE,
    },
    {
        id: "faq7",
        question: "Du học Mỹ cần chuẩn bị gì?",
        answer: "Cần SAT và tốt nghiệp THPT.",
        category: "Mỹ",
        status: EStatus.ACTIVE,
    },
    {
        id: "faq8",
        question: "Học phí du học Pháp bao nhiêu?",
        answer: "Khoảng $22,000/năm.",
        category: "Pháp",
        status: EStatus.ACTIVE,
    },
    {
        id: "faq9",
        question: "Du học Singapore cần IELTS bao nhiêu?",
        answer: "Cần IELTS 6.0.",
        category: "Singapore",
        status: EStatus.ACTIVE,
    },
    {
        id: "faq10",
        question: "Du học Thụy Sĩ cần chứng chỉ gì?",
        answer: "Cần B2 tiếng Anh.",
        category: "Thụy Sĩ",
        status: EStatus.ACTIVE,
    },
];
