export const mockData = {
  programs: [
    {
      id: '1',
      title: 'Du học Thạc sĩ Hàn Quốc',
      description: 'Chương trình du học thạc sĩ toàn diện với học bổng lên tới 100% học phí và cơ hội thực tập có lương',
      country: 'Hàn Quốc',
      duration: '2 năm',
      tuition: '15,000 - 25,000 USD/năm',
      requirements: ['IELTS 6.0+ hoặc TOPIK 4+', 'Bằng cử nhân', 'GPA 2.5+', 'Thư giới thiệu'],
      benefits: ['Học bổng 100%', 'Thực tập có lương', 'Cơ hội định cư', 'Bảo hiểm y tế'],
      imageUrl: '/api/placeholder/400/300',
      featured: true,
    },
    {
      id: '2',
      title: 'Du học Nhật Bản - Chương trình đặc biệt',
      description: 'Học tập và làm việc tại đất nước mặt trời mọc với nền giáo dục chất lượng cao và cơ hội việc làm tuyệt vời',
      country: 'Nhật Bản',
      duration: '1-4 năm',
      tuition: '8,000 - 15,000 USD/năm',
      requirements: ['Tiếng Nhật N3+ hoặc IELTS 6.0+', 'Bằng tốt nghiệp THPT', 'Chứng minh tài chính'],
      benefits: ['Làm thêm 28h/tuần', 'Học bổng MEXT', 'Cơ hội việc làm cao', 'Văn hóa độc đáo'],
      imageUrl: '/api/placeholder/400/300',
      featured: true,
    },
    {
      id: '3',
      title: 'Du học Đài Loan - Chi phí tối ưu',
      description: 'Chi phí hợp lý, chất lượng giáo dục cao và văn hóa gần gũi với Việt Nam, dễ dàng thích nghi',
      country: 'Đài Loan',
      duration: '1-4 năm',
      tuition: '3,000 - 8,000 USD/năm',
      requirements: ['IELTS 5.5+ hoặc HSK 4+', 'Bằng tốt nghiệp THPT', 'GPA 2.0+'],
      benefits: ['Chi phí sinh hoạt thấp', 'Học bổng chính phủ', 'Dễ xin visa', 'Cộng đồng người Việt lớn'],
      imageUrl: '/api/placeholder/400/300',
      featured: true,
    },
    {
      id: '4',
      title: 'Du học Đức - Miễn học phí',
      description: 'Hệ thống giáo dục hàng đầu châu Âu với nhiều trường đại học công lập miễn học phí',
      country: 'Đức',
      duration: '2-3 năm',
      tuition: '0 - 3,000 EUR/năm',
      requirements: ['IELTS 6.5+ hoặc TestDaF', 'Bằng cử nhân', 'GPA 3.0+', 'Động cơ học tập rõ ràng'],
      benefits: ['Miễn học phí', 'Cơ hội nghiên cứu', 'Thị trường lao động EU', 'Nền kinh tế mạnh'],
      imageUrl: '/api/placeholder/400/300',
      featured: false,
    },
    {
      id: '5',
      title: 'Du học Úc - Chất lượng hàng đầu',
      description: 'Nền giáo dục hàng đầu thế giới với môi trường học tập đa văn hóa và cơ hội định cư cao',
      country: 'Úc',
      duration: '1.5-3 năm',
      tuition: '25,000 - 45,000 AUD/năm',
      requirements: ['IELTS 6.5+', 'Bằng cử nhân', 'GPA 2.7+', 'Chứng minh tài chính'],
      benefits: ['Chất lượng giáo dục top 10', 'Cơ hội định cư cao', 'Làm thêm 40h/2 tuần', 'Môi trường đa văn hóa'],
      imageUrl: '/api/placeholder/400/300',
      featured: false,
    },
    {
      id: '6',
      title: 'Du học Mỹ - Ivy League',
      description: 'Cơ hội học tập tại các trường đại học danh tiếng nhất thế giới với nguồn học bổng phong phú',
      country: 'Mỹ',
      duration: '2-4 năm',
      tuition: '30,000 - 70,000 USD/năm',
      requirements: ['IELTS 7.0+ hoặc TOEFL 100+', 'GRE/GMAT', 'Bằng cử nhân xuất sắc', 'Kinh nghiệm nghiên cứu'],
      benefits: ['Trường top thế giới', 'Mạng lưới alumni mạnh', 'Cơ hội nghiên cứu', 'Thị trường việc làm lớn'],
      imageUrl: '/api/placeholder/400/300',
      featured: false,
    },
  ] as IProgram[],

  blogs: [
    {
      id: '1',
      title: 'Kinh nghiệm xin visa du học Hàn Quốc 2024 - Tỷ lệ thành công 98%',
      excerpt: 'Hướng dẫn chi tiết quy trình xin visa du học Hàn Quốc, những lưu ý quan trọng và bí quyết tăng tỷ lệ thành công từ chuyên gia.',
      content: 'Nội dung chi tiết về visa...',
      author: 'Nguyễn Minh Tuấn',
      publishedAt: '2024-03-15',
      imageUrl: '/api/placeholder/600/400',
      category: 'Visa & Thủ tục',
      slug: 'kinh-nghiem-xin-visa-du-hoc-han-quoc-2024',
    },
    {
      id: '2',
      title: 'Top 10 trường đại học tốt nhất Nhật Bản cho sinh viên quốc tế',
      excerpt: 'Danh sách các trường đại học hàng đầu Nhật Bản dành cho sinh viên quốc tế, học phí, điều kiện tuyển sinh và cơ hội học bổng.',
      content: 'Nội dung về trường đại học Nhật Bản...',
      author: 'Trần Thị Lan',
      publishedAt: '2024-03-10',
      imageUrl: '/api/placeholder/600/400',
      category: 'Chương trình học',
      slug: 'top-10-truong-dai-hoc-tot-nhat-nhat-ban',
    },
    {
      id: '3',
      title: 'Chi phí du học Đài Loan 2024 - Ngân sách từ 100 triệu/năm',
      excerpt: 'Phân tích chi tiết chi phí du học Đài Loan bao gồm học phí, sinh hoạt phí và các khoản chi phí khác cho sinh viên Việt Nam.',
      content: 'Nội dung về chi phí du học...',
      author: 'Lê Văn Hùng',
      publishedAt: '2024-03-05',
      imageUrl: '/api/placeholder/600/400',
      category: 'Chi phí du học',
      slug: 'chi-phi-du-hoc-dai-loan-2024',
    },
    {
      id: '4',
      title: 'Học bổng toàn phần du học Đức - Cơ hội vàng cho sinh viên Việt',
      excerpt: 'Tổng hợp các chương trình học bổng du học Đức dành cho sinh viên Việt Nam, điều kiện và cách thức đăng ký.',
      content: 'Nội dung về học bổng Đức...',
      author: 'Phạm Thị Mai',
      publishedAt: '2024-02-28',
      imageUrl: '/api/placeholder/600/400',
      category: 'Học bổng',
      slug: 'hoc-bong-toan-phan-du-hoc-duc',
    },
    {
      id: '5',
      title: 'Cuộc sống du học sinh tại Úc - Kinh nghiệm thực tế từ A-Z',
      excerpt: 'Chia sẻ kinh nghiệm sống và học tập tại Úc từ những du học sinh đang theo học, giúp bạn chuẩn bị tốt nhất.',
      content: 'Nội dung về cuộc sống du học...',
      author: 'Hoàng Minh Đức',
      publishedAt: '2024-02-20',
      imageUrl: '/api/placeholder/600/400',
      category: 'Kinh nghiệm',
      slug: 'cuoc-song-du-hoc-sinh-tai-uc',
    },
    {
      id: '6',
      title: 'Chuẩn bị hồ sơ du học Mỹ - Checklist đầy đủ từ chuyên gia',
      excerpt: 'Danh sách chi tiết các giấy tờ cần thiết cho hồ sơ du học Mỹ, thời gian chuẩn bị và những lưu ý quan trọng.',
      content: 'Nội dung về hồ sơ du học Mỹ...',
      author: 'Võ Thị Hoa',
      publishedAt: '2024-02-15',
      imageUrl: '/api/placeholder/600/400',
      category: 'Hồ sơ du học',
      slug: 'chuan-bi-ho-so-du-hoc-my',
    },
  ] as IBlog[],

  faqs: [
    {
      id: '1',
      question: 'Tôi cần chuẩn bị gì để du học Hàn Quốc?',
      answer: 'Để du học Hàn Quốc, bạn cần chuẩn bị: (1) Bằng cấp và bảng điểm đã được công chứng, (2) Chứng chỉ tiếng Hàn (TOPIK) hoặc tiếng Anh (IELTS/TOEFL), (3) Chứng minh tài chính, (4) Hộ chiếu còn hạn, (5) Đơn xin học, (6) Thư giới thiệu, (7) Kế hoạch học tập. Chúng tôi sẽ hỗ trợ bạn chuẩn bị đầy đủ hồ sơ.',
      category: 'Hồ sơ du học',
    },
    {
      id: '2',
      question: 'Chi phí du học Nhật Bản khoảng bao nhiêu?',
      answer: 'Chi phí du học Nhật Bản dao động từ 200-400 triệu VNĐ/năm, bao gồm: Học phí: 80-150 triệu VNĐ/năm, Sinh hoạt phí: 120-250 triệu VNĐ/năm. Tuy nhiên, sinh viên có thể làm thêm 28h/tuần để trang trải chi phí, và có nhiều chương trình học bổng hỗ trợ.',
      category: 'Chi phí',
    },
    {
      id: '3',
      question: 'Thời gian xử lý visa du học mất bao lâu?',
      answer: 'Thời gian xử lý visa du học khác nhau tùy quốc gia: Hàn Quốc: 2-4 tuần, Nhật Bản: 3-6 tuần, Đài Loan: 2-3 tuần, Đức: 4-8 tuần, Úc: 4-6 tuần, Mỹ: 6-12 tuần. Chúng tôi khuyên bạn nên nộp hồ sơ sớm ít nhất 3-4 tháng trước khi khởi hành.',
      category: 'Visa',
    },
    {
      id: '4',
      question: 'Có cần biết tiếng nước sở tại không?',
      answer: 'Tùy thuộc vào quốc gia và chương trình học: Các nước châu Á (Hàn Quốc, Nhật Bản, Đài Loan): Nên có kiến thức cơ bản về ngôn ngữ địa phương. Các nước phương Tây (Đức, Úc, Mỹ): Chủ yếu học bằng tiếng Anh. Chúng tôi có các khóa học ngôn ngữ chuẩn bị trước khi xuất cảnh.',
      category: 'Ngôn ngữ',
    },
    {
      id: '5',
      question: 'Sau khi tốt nghiệp có cơ hội định cư không?',
      answer: 'Cơ hội định cư sau tốt nghiệp: Úc: Rất cao với các chính sách hỗ trợ, Đức: Tốt với ngành STEM và kỹ thuật, Canada: Chính sách thu hút nhân tài, Hàn Quốc/Nhật Bản: Khó hơn nhưng có thể với việc làm ổn định, Mỹ: Qua chương trình H1B và EB visa. Chúng tôi tư vấn định hướng phù hợp với từng cá nhân.',
      category: 'Định cư',
    },
    {
      id: '6',
      question: 'Việt Âu hỗ trợ gì trong quá trình du học?',
      answer: 'Chúng tôi hỗ trợ toàn diện: (1) Tư vấn chọn trường và ngành học phù hợp, (2) Chuẩn bị hồ sơ đầy đủ, (3) Hỗ trợ xin visa, (4) Đón tiếp tại sân bay, (5) Hỗ trợ tìm chỗ ở, (6) Hướng dẫn thủ tục nhập học, (7) Hỗ trợ trong quá trình học tập, (8) Tư vấn thực tập và việc làm.',
      category: 'Dịch vụ',
    },
  ] as IFAQ[],

  testimonials: [
    {
      id: '1',
      name: 'Nguyễn Thị Hương',
      program: 'Du học Thạc sĩ Hàn Quốc',
      university: 'Seoul National University',
      rating: 5,
      comment: 'Việt Âu đã hỗ trợ tôi từ A-Z trong quá trình du học. Từ việc chọn trường, chuẩn bị hồ sơ đến xin visa đều rất chuyên nghiệp. Hiện tôi đã tốt nghiệp và có công việc tốt tại Seoul.',
      image: '/api/placeholder/100/100',
      year: 2023,
    },
    {
      id: '2',
      name: 'Trần Minh Khoa',
      program: 'Du học Nhật Bản',
      university: 'University of Tokyo',
      rating: 5,
      comment: 'Ban đầu tôi rất lo lắng về việc du học Nhật Bản vì không biết tiếng. Nhưng team Việt Âu đã hỗ trợ tôi học tiếng Nhật từ cơ bản và kết quả vượt ngoài mong đợi. Cảm ơn rất nhiều!',
      image: '/api/placeholder/100/100',
      year: 2023,
    },
    {
      id: '3',
      name: 'Lê Thị Mai',
      program: 'Du học Đài Loan',
      university: 'National Đài Loan University',
      rating: 5,
      comment: 'Chi phí du học Đài Loan rất hợp lý và chất lượng giáo dục tuyệt vời. Việt Âu đã giúp tôi chọn được trường và ngành học phù hợp. Cuộc sống ở đây rất thoải mái và an toàn.',
      image: '/api/placeholder/100/100',
      year: 2024,
    },
  ],

  jobs: [
    {
      id: "1",
      title: "Chế Biến Nông Sản",
      country: "Japan",
      image: "/images/jobs/agricultural-processing.jpg",
      positions: 3,
      location: "KAGOSHIMA",
      salary: "147.715 Yên/Tháng",
      applicationDeadline: "26/09/2025",
      estimatedDeparture: "4 - 6 tháng sau khi thi đỗ phỏng vấn",
      requirements: [
        "Nam/Nữ 18-35 tuổi",
        "Sức khỏe tốt",
        "Không yêu cầu kinh nghiệm",
      ],
      benefits: ["Lương ổn định", "Bảo hiểm y tế", "Nhà ở miễn phí"],
      description: "Làm việc tại nhà máy chế biến nông sản hiện đại",
      company: "ABC Foods Co., Ltd",
      workType: "Toàn thời gian",
      featured: true,
    },
    {
      id: "2",
      title: "Vệ Sinh Khách Sạn",
      country: "Japan",
      imageUrl: "/images/jobs/hotel-cleaning.jpg",
      positions: 3,
      location: "OITA",
      salary: "163.400 Yên/Tháng",
      applicationDeadline: "03/10/2025",
      estimatedDeparture: "4 - 6 tháng sau khi thi đỗ phỏng vấn",
      requirements: ["Nữ 20-40 tuổi", "Cẩn thận, tỉ mỉ", "Tiếng Nhật cơ bản"],
      benefits: ["Lương cao", "Môi trường sạch sẽ", "Được đào tạo"],
      description: "Vệ sinh phòng khách sạn 4 sao",
      company: "Oita Grand Hotel",
      workType: "Toàn thời gian",
    },
    {
      id: "3",
      title: "Chế Biến Thực Phẩm",
      country: "Japan",
      imageUrl: "/images/jobs/food-processing.jpg",
      positions: 2,
      location: "KUMAMOTO",
      salary: "153.000 Yên/Tháng",
      applicationDeadline: "26/09/2025",
      estimatedDeparture: "4 - 6 tháng sau khi thi đỗ phỏng vấn",
      requirements: ["Nam/Nữ 18-32 tuổi", "Không sợ lạnh", "Có trách nhiệm"],
      benefits: ["Ăn trưa miễn phí", "Thưởng hiệu suất", "Nghỉ phép có lương"],
      description: "Chế biến và đóng gói thực phẩm đông lạnh",
      company: "Kumamoto Food Industries",
      workType: "Ca làm việc",
    },
    {
      id: "4",
      title: "Xây Dựng",
      country: "Japan",
      imageUrl: "/images/jobs/construction.jpg",
      positions: 1,
      location: "KAGOSHIMA",
      salary: "155.481 Yên/Tháng",
      applicationDeadline: "26/09/2025",
      estimatedDeparture: "4 - 6 tháng sau khi thi đỗ phỏng vấn",
      requirements: ["Nam 18-35 tuổi", "Khỏe mạnh", "Không sợ độ cao"],
      benefits: ["Lương theo năng lực", "Bảo hiểm tai nạn", "Phụ cấp kỹ thuật"],
      description: "Thi công xây dựng công trình dân dụng",
      company: "Kagoshima Construction Co.",
      workType: "Toàn thời gian",
      featured: true,
    },
    {
      id: "5",
      title: "Điện Tử",
      country: "Korea",
      imageUrl: "/images/jobs/electronics.jpg",
      positions: 5,
      location: "SEOUL",
      salary: "1.800.000 Won/Tháng",
      applicationDeadline: "15/10/2025",
      estimatedDeparture: "3 - 5 tháng sau khi thi đỗ phỏng vấn",
      requirements: ["Nam/Nữ 20-30 tuổi", "Tốt nghiệp THPT", "Khéo léo"],
      benefits: ["Lương cao", "Làm việc hiện đại", "Cơ hội thăng tiến"],
      description: "Lắp ráp linh kiện điện tử tại nhà máy Samsung",
      company: "Samsung Electronics",
      workType: "Toàn thời gian",
    },
    {
      id: "6",
      title: "Chăm Sóc Người Già",
      country: "Germany",
      imageUrl: "/images/jobs/elderly-care.jpg",
      positions: 2,
      location: "BERLIN",
      salary: "2.500 EUR/Tháng",
      applicationDeadline: "20/10/2025",
      estimatedDeparture: "6 - 8 tháng sau khi thi đỗ phỏng vấn",
      requirements: ["Nữ 22-40 tuổi", "Có chứng chỉ điều dưỡng", "Tiếng Đức B1"],
      benefits: ["Lương cao nhất", "Phúc lợi tốt", "Cơ hội định cư"],
      description: "Chăm sóc người cao tuổi tại viện dưỡng lão",
      company: "Berlin Care Center",
      workType: "Toàn thời gian",
    },
  ] as IJob[],
};