import { EContactStatus, EStatus, EUserStatus } from "../types/enum";

// User mock data
export const mockUsers: IUser[] = [
    {
        _id: "user1",
        email: "nguyenvana@example.com",
        password: "password123",
        name: "Nguyễn Văn An",
        phone: "0901234567",
        status: EUserStatus.PENDING,
    },
    {
        _id: "user2",
        email: "tranthib@example.com",
        password: "password456",
        name: "Trần Thị Bích",
        phone: "0902345678",
        status: EUserStatus.PENDING,
    },
    {
        _id: "user3",
        email: "levanc@example.com",
        password: "password789",
        name: "Lê Văn Cường",
        phone: "0903456789",
        status: EUserStatus.PENDING,
    },
    {
        _id: "user4",
        email: "phamthid@example.com",
        password: "password101",
        name: "Phạm Thị Dung",
        phone: "0904567890",
        status: EUserStatus.PENDING,
    },
    {
        _id: "user5",
        email: "vovane@example.com",
        password: "password202",
        name: "Võ Văn Em",
        phone: "0905678901",
        status: EUserStatus.PENDING,
    },
    {
        _id: "user6",
        email: "dangthif@example.com",
        password: "password303",
        name: "Đặng Thị Hoa",
        phone: "0906789012",
        status: EUserStatus.PENDING,
    },
    {
        _id: "user7",
        email: "buivang@example.com",
        password: "password404",
        name: "Bùi Văn Giang",
        phone: "0907890123",
        status: EUserStatus.PENDING,
    },
    {
        _id: "user8",
        email: "hothih@example.com",
        password: "password505",
        name: "Hồ Thị Hà",
        phone: "0908901234",
        status: EUserStatus.PENDING,
    },
    {
        _id: "user9",
        email: "nguyenvani@example.com",
        password: "password606",
        name: "Nguyễn Văn Huy",
        phone: "0909012345",
        status: EUserStatus.PENDING,
    },
    {
        _id: "user10",
        email: "phanthik@example.com",
        password: "password707",
        name: "Phan Thị Lan",
        phone: "0910123456",
        status: EUserStatus.PENDING,
    },
];

// Program mock data
export const mockPrograms: IProgram[] = [
    {
        _id: "program1",
        title: "Du học Úc",
        description: "Chương trình du học tại Úc với nhiều ưu đãi.",
        country: "Úc",
        duration: "2 năm",
        tuition: "500,000,000 VND",
        opportunities: "Cơ hội việc làm sau tốt nghiệp",
        about: "Úc là một trong những điểm đến du học hàng đầu với nền giáo dục chất lượng cao.",
        requirements: "IELTS 6.0, Tốt nghiệp THPT",
        benefits: "Cơ hội việc làm, Định cư",
        imageUrl: "/images/mockPrograms/australia.jpg",
        featured: true,
        createdAt: "2025-01-01",
        updatedAt: "2025-06-01",
        status: EStatus.ACTIVE,
    },
    {
        _id: "program2",
        title: "Du học Canada",
        description: "Chương trình du học tại Canada.",
        country: "Canada",
        duration: "3 năm",
        tuition: "625,000,000 VND",
        opportunities: "Cơ hội việc làm sau tốt nghiệp",
        about: "Canada nổi tiếng với môi trường học tập thân thiện và đa văn hóa.",
        requirements: "IELTS 6.5, Tốt nghiệp THPT",
        benefits: "Cơ hội việc làm, Học bổng",
        imageUrl: "/images/mockPrograms/canada.jpg",
        featured: false,
        createdAt: "2025-02-01",
        updatedAt: "2025-06-02",
        status: EStatus.ACTIVE,
    },
    {
        _id: "program3",
        title: "Du học Đức",
        description: "Chương trình du học tại Đức.",
        country: "Đức",
        duration: "2 năm",
        tuition: "450,000,000 VND",
        opportunities: "Cơ hội việc làm sau tốt nghiệp",
        about: "Đức có nền giáo dục kỹ thuật và nghiên cứu hàng đầu thế giới.",
        requirements: "B1 tiếng Đức, Tốt nghiệp THPT",
        benefits: "Miễn học phí, Cơ hội việc làm",
        imageUrl: "/images/mockPrograms/germany.jpg",
        featured: true,
        createdAt: "2025-03-01",
        updatedAt: "2025-06-03",
        status: EStatus.ACTIVE,
    },
    {
        _id: "program4",
        title: "Du học Nhật Bản",
        description: "Chương trình du học tại Nhật Bản.",
        country: "Nhật Bản",
        duration: "1 năm",
        tuition: "375,000,000 VND",
        opportunities: "Cơ hội việc làm sau tốt nghiệp",
        about: "Nhật Bản có nền công nghiệp phát triển và môi trường học tập chuyên nghiệp.",
        requirements: "N3 tiếng Nhật, Tốt nghiệp THPT",
        benefits: "Cơ hội việc làm, Học bổng",
        imageUrl: "/images/mockPrograms/japan.jpg",
        featured: false,
        createdAt: "2025-04-01",
        updatedAt: "2025-06-04",
        status: EStatus.ACTIVE,
    },
    {
        _id: "program5",
        title: "Du học Hàn Quốc",
        description: "Chương trình du học tại Hàn Quốc.",
        country: "Hàn Quốc",
        duration: "2 năm",
        tuition: "425,000,000 VND",
        opportunities: "Cơ hội việc làm sau tốt nghiệp",
        about: "Hàn Quốc có nền giáo dục hiện đại và môi trường học tập năng động.",
        requirements: "TOPIK 3, Tốt nghiệp THPT",
        benefits: "Cơ hội việc làm, Định cư",
        imageUrl: "/images/mockPrograms/korea.jpg",
        featured: true,
        createdAt: "2025-05-01",
        updatedAt: "2025-06-05",
        status: EStatus.ACTIVE,
    },
    {
        _id: "program6",
        title: "Du học Đài Loan",
        description: "Chương trình du học tại Đài Loan.",
        country: "Đài Loan",
        duration: "1.5 năm",
        tuition: "400,000,000 VND",
        opportunities: "Cơ hội việc làm sau tốt nghiệp",
        about: "Đài Loan có nền giáo dục chất lượng cao với chi phí hợp lý.",
        requirements: "TOCFL 3, Tốt nghiệp THPT",
        benefits: "Cơ hội việc làm, Học bổng",
        imageUrl: "/images/mockPrograms/taiwan.jpg",
        featured: false,
        createdAt: "2025-06-01",
        updatedAt: "2025-06-06",
        status: EStatus.ACTIVE,
    },
    {
        _id: "program7",
        title: "Du học Mỹ",
        description: "Chương trình du học tại Mỹ.",
        country: "Mỹ",
        duration: "4 năm",
        tuition: "750,000,000 VND",
        opportunities: "Cơ hội việc làm sau tốt nghiệp",
        about: "Mỹ có hệ thống giáo dục hàng đầu thế giới với nhiều cơ hội nghề nghiệp.",
        requirements: "SAT, Tốt nghiệp THPT",
        benefits: "Cơ hội việc làm, Học bổng",
        imageUrl: "/images/mockPrograms/usa.jpg",
        featured: true,
        createdAt: "2025-07-01",
        updatedAt: "2025-07-07",
        status: EStatus.ACTIVE,
    },
    {
        _id: "program8",
        title: "Du học Pháp",
        description: "Chương trình du học tại Pháp.",
        country: "Pháp",
        duration: "3 năm",
        tuition: "550,000,000 VND",
        opportunities: "Cơ hội việc làm sau tốt nghiệp",
        about: "Pháp có nền giáo dục lâu đời và môi trường học tập lý tưởng.",
        requirements: "B2 tiếng Pháp, Tốt nghiệp THPT",
        benefits: "Cơ hội việc làm, Học bổng",
        imageUrl: "/images/mockPrograms/france.jpg",
        featured: false,
        createdAt: "2025-08-01",
        updatedAt: "2025-08-08",
        status: EStatus.ACTIVE,
    },
    {
        _id: "program9",
        title: "Du học Singapore",
        description: "Chương trình du học tại Singapore.",
        country: "Singapore",
        duration: "2 năm",
        tuition: "475,000,000 VND",
        opportunities: "Cơ hội việc làm sau tốt nghiệp",
        about: "Singapore là trung tâm giáo dục và kinh tế của châu Á.",
        requirements: "IELTS 6.0, Tốt nghiệp THPT",
        benefits: "Cơ hội việc làm, Học bổng",
        imageUrl: "/images/mockPrograms/singapore.jpg",
        featured: true,
        createdAt: "2025-09-01",
        updatedAt: "2025-09-09",
        status: EStatus.ACTIVE,
    },
    {
        _id: "program10",
        title: "Du học Thụy Sĩ",
        description: "Chương trình du học tại Thụy Sĩ.",
        country: "Thụy Sĩ",
        duration: "2 năm",
        tuition: "525,000,000 VND",
        opportunities: "Cơ hội việc làm sau tốt nghiệp",
        about: "Thụy Sĩ có nền giáo dục chất lượng cao và môi trường sống tuyệt vời.",
        requirements: "B2 tiếng Anh, Tốt nghiệp THPT",
        benefits: "Cơ hội việc làm, Học bổng",
        imageUrl: "/images/mockPrograms/switzerland.jpg",
        featured: false,
        createdAt: "2025-10-01",
        updatedAt: "2025-10-10",
        status: EStatus.ACTIVE,
    },
];

// Job mock data
export const mockJobs: IJob[] = [
    {
        _id: "job1",
        title: "Nhân viên văn phòng Úc",
        country: "Úc",
        imageUrl: "/images/jobs/australia.jpg",
        positions: 5,
        location: "Sydney",
        salary: "75,000,000 VND/tháng",
        applicationDeadline: "2025-02-01",
        estimatedDeparture: "2025-03-01",
        requirements: "Tiếng Anh tốt, Kinh nghiệm văn phòng",
        benefits: "Bảo hiểm, Thưởng",
        description: "Công việc văn phòng tại Úc.",
        company: "AUS Office",
        workType: "Full-time",
        featured: true,
        workingHours: "40h/tuần",
        overtime: "Có",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Văn phòng hiện đại",
        trainingPeriod: "1 tháng",
        status: EStatus.ACTIVE,
    },
    {
        _id: "job2",
        title: "Nhân viên nhà hàng Canada",
        country: "Canada",
        imageUrl: "/images/jobs/canada.jpg",
        positions: 3,
        location: "Toronto",
        salary: "70,000,000 VND/tháng",
        applicationDeadline: "2025-03-01",
        estimatedDeparture: "2025-04-01",
        requirements: "Tiếng Anh cơ bản, Kinh nghiệm nhà hàng",
        benefits: "Bảo hiểm, Ăn trưa miễn phí",
        description: "Công việc nhà hàng tại Canada.",
        company: "CAN Restaurant",
        workType: "Part-time",
        featured: false,
        workingHours: "30h/tuần",
        overtime: "Không",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Nhà hàng sang trọng",
        trainingPeriod: "2 tuần",
        status: EStatus.ACTIVE,
    },
    {
        _id: "job3",
        title: "Kỹ sư Đức",
        country: "Đức",
        imageUrl: "/images/jobs/germany.jpg",
        positions: 2,
        location: "Berlin",
        salary: "100,000,000 VND/tháng",
        applicationDeadline: "2025-04-01",
        estimatedDeparture: "2025-05-01",
        requirements: "Tiếng Đức B1, Bằng kỹ sư",
        benefits: "Bảo hiểm, Thưởng",
        description: "Công việc kỹ sư tại Đức.",
        company: "GER Engineering",
        workType: "Full-time",
        featured: true,
        workingHours: "40h/tuần",
        overtime: "Có",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Xưởng hiện đại",
        trainingPeriod: "2 tháng",
        status: EStatus.ACTIVE,
    },
    {
        _id: "job4",
        title: "Nhân viên khách sạn Nhật Bản",
        country: "Nhật Bản",
        imageUrl: "/images/jobs/japan.jpg",
        positions: 4,
        location: "Tokyo",
        salary: "62,500,000 VND/tháng",
        applicationDeadline: "2025-05-01",
        estimatedDeparture: "2025-06-01",
        requirements: "Tiếng Nhật N3, Kinh nghiệm khách sạn",
        benefits: "Bảo hiểm, Ăn trưa miễn phí",
        description: "Công việc khách sạn tại Nhật Bản.",
        company: "JPN Hotel",
        workType: "Full-time",
        featured: false,
        workingHours: "40h/tuần",
        overtime: "Có",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Khách sạn 5 sao",
        trainingPeriod: "1 tháng",
        status: EStatus.ACTIVE,
    },
    {
        _id: "job5",
        title: "Nhân viên sản xuất Hàn Quốc",
        country: "Hàn Quốc",
        imageUrl: "/images/jobs/korea.jpg",
        positions: 6,
        location: "Seoul",
        salary: "67,500,000 VND/tháng",
        applicationDeadline: "2025-06-01",
        estimatedDeparture: "2025-07-01",
        requirements: "Tiếng Hàn TOPIK 3, Kinh nghiệm sản xuất",
        benefits: "Bảo hiểm, Thưởng",
        description: "Công việc sản xuất tại Hàn Quốc.",
        company: "KOR Factory",
        workType: "Full-time",
        featured: true,
        workingHours: "40h/tuần",
        overtime: "Có",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Nhà máy hiện đại",
        trainingPeriod: "2 tháng",
        status: EStatus.ACTIVE,
    },
    {
        _id: "job6",
        title: "Nhân viên văn phòng Đài Loan",
        country: "Đài Loan",
        imageUrl: "/images/jobs/taiwan.jpg",
        positions: 2,
        location: "Taipei",
        salary: "65,000,000 VND/tháng",
        applicationDeadline: "2025-07-01",
        estimatedDeparture: "2025-08-01",
        requirements: "Tiếng Trung TOCFL 3, Kinh nghiệm văn phòng",
        benefits: "Bảo hiểm, Thưởng",
        description: "Công việc văn phòng tại Đài Loan.",
        company: "TWN Office",
        workType: "Part-time",
        featured: false,
        workingHours: "30h/tuần",
        overtime: "Không",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Văn phòng hiện đại",
        trainingPeriod: "1 tháng",
        status: EStatus.ACTIVE,
    },
    {
        _id: "job7",
        title: "Nhân viên nhà hàng Mỹ",
        country: "Mỹ",
        imageUrl: "/images/jobs/usa.jpg",
        positions: 3,
        location: "New York",
        salary: "80,000,000 VND/tháng",
        applicationDeadline: "2025-08-01",
        estimatedDeparture: "2025-09-01",
        requirements: "Tiếng Anh tốt, Kinh nghiệm nhà hàng",
        benefits: "Bảo hiểm, Ăn trưa miễn phí",
        description: "Công việc nhà hàng tại Mỹ.",
        company: "USA Restaurant",
        workType: "Full-time",
        featured: true,
        workingHours: "40h/tuần",
        overtime: "Có",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Nhà hàng sang trọng",
        trainingPeriod: "2 tuần",
        status: EStatus.ACTIVE,
    },
    {
        _id: "job8",
        title: "Nhân viên khách sạn Pháp",
        country: "Pháp",
        imageUrl: "/images/jobs/france.jpg",
        positions: 2,
        location: "Paris",
        salary: "72,500,000 VND/tháng",
        applicationDeadline: "2025-09-01",
        estimatedDeparture: "2025-10-01",
        requirements: "Tiếng Pháp B2, Kinh nghiệm khách sạn",
        benefits: "Bảo hiểm, Ăn trưa miễn phí",
        description: "Công việc khách sạn tại Pháp.",
        company: "FRA Hotel",
        workType: "Full-time",
        featured: false,
        workingHours: "40h/tuần",
        overtime: "Có",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Khách sạn 5 sao",
        trainingPeriod: "1 tháng",
        status: EStatus.ACTIVE,
    },
    {
        _id: "job9",
        title: "Nhân viên sản xuất Singapore",
        country: "Singapore",
        imageUrl: "/images/jobs/singapore.jpg",
        positions: 4,
        location: "Singapore",
        salary: "70,000,000 VND/tháng",
        applicationDeadline: "2025-10-01",
        estimatedDeparture: "2025-11-01",
        requirements: "Tiếng Anh tốt, Kinh nghiệm sản xuất",
        benefits: "Bảo hiểm, Thưởng",
        description: "Công việc sản xuất tại Singapore.",
        company: "SG Factory",
        workType: "Full-time",
        featured: true,
        workingHours: "40h/tuần",
        overtime: "Có",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Nhà máy hiện đại",
        trainingPeriod: "2 tháng",
        status: EStatus.ACTIVE,
    },
    {
        _id: "job10",
        title: "Nhân viên văn phòng Thụy Sĩ",
        country: "Thụy Sĩ",
        imageUrl: "/images/jobs/switzerland.jpg",
        positions: 2,
        location: "Zurich",
        salary: "77,500,000 VND/tháng",
        applicationDeadline: "2025-11-01",
        estimatedDeparture: "2025-12-01",
        requirements: "Tiếng Anh B2, Kinh nghiệm văn phòng",
        benefits: "Bảo hiểm, Thưởng",
        description: "Công việc văn phòng tại Thụy Sĩ.",
        company: "SUI Office",
        workType: "Full-time",
        featured: false,
        workingHours: "40h/tuần",
        overtime: "Có",
        accommodation: "Có hỗ trợ",
        workEnvironment: "Văn phòng hiện đại",
        trainingPeriod: "1 tháng",
        status: EStatus.ACTIVE,
    },
];

// Contact mock data
export const mockContacts: IContact[] = [
    {
        _id: "contact1",
        name: "Nguyen Van A",
        email: "nva@example.com",
        phone: "0912345678",
        program: mockPrograms[0].title,
        message: "Tôi muốn biết thêm về chương trình Úc.",
        resolvedBy: mockUsers[0].name,
        resolvedAt: "2025-01-15",
        createdAt: "2025-01-10",
        updatedAt: "2025-01-15",
        status: EContactStatus.RESOLVED,
    },
    {
        _id: "contact2",
        name: "Tran Thi B",
        email: "ttb@example.com",
        phone: "0923456789",
        program: mockPrograms[1].title,
        message: "Tôi muốn đăng ký chương trình Canada.",
        resolvedBy: mockUsers[1].name,
        resolvedAt: "2025-02-20",
        createdAt: "2025-02-15",
        updatedAt: "2025-02-20",
        status: EContactStatus.RESOLVED,
    },
    {
        _id: "contact3",
        name: "Le Van C",
        email: "lvc@example.com",
        phone: "0934567890",
        program: mockPrograms[2].title,
        message: "Tôi cần tư vấn về du học Đức.",
        resolvedBy: mockUsers[2].name,
        resolvedAt: "2025-03-25",
        createdAt: "2025-03-20",
        updatedAt: "2025-03-25",
        status: EContactStatus.RESOLVED,
    },
    {
        _id: "contact4",
        name: "Pham Thi D",
        email: "ptd@example.com",
        phone: "0945678901",
        program: mockPrograms[3].title,
        message: "Tôi muốn hỏi về chương trình Nhật Bản.",
        resolvedBy: mockUsers[3].name,
        resolvedAt: "2025-04-30",
        createdAt: "2025-04-25",
        updatedAt: "2025-04-30",
        status: EContactStatus.RESOLVED,
    },
    {
        _id: "contact5",
        name: "Vo Van E",
        email: "vve@example.com",
        phone: "0956789012",
        program: mockPrograms[4].title,
        message: "Tôi muốn biết về du học Hàn Quốc.",
        resolvedBy: mockUsers[4].name,
        resolvedAt: "2025-05-05",
        createdAt: "2025-05-01",
        updatedAt: "2025-05-05",
        status: EContactStatus.RESOLVED,
    },
    {
        _id: "contact6",
        name: "Dang Thi F",
        email: "dtf@example.com",
        phone: "0967890123",
        program: mockPrograms[5].title,
        message: "Tôi muốn hỏi về chương trình Đài Loan.",
        resolvedBy: mockUsers[5].name,
        resolvedAt: "2025-06-10",
        createdAt: "2025-06-05",
        updatedAt: "2025-06-10",
        status: EContactStatus.RESOLVED,
    },
    {
        _id: "contact7",
        name: "Bui Van G",
        email: "bvg@example.com",
        phone: "0978901234",
        program: mockPrograms[6].title,
        message: "Tôi muốn đăng ký chương trình Mỹ.",
        resolvedBy: mockUsers[6].name,
        resolvedAt: "2025-07-15",
        createdAt: "2025-07-10",
        updatedAt: "2025-07-15",
        status: EContactStatus.RESOLVED,
    },
    {
        _id: "contact8",
        name: "Ho Thi H",
        email: "hth@example.com",
        phone: "0989012345",
        program: mockPrograms[7].title,
        message: "Tôi muốn hỏi về chương trình Pháp.",
        resolvedBy: mockUsers[7].name,
        resolvedAt: "2025-08-20",
        createdAt: "2025-08-15",
        updatedAt: "2025-08-20",
        status: EContactStatus.RESOLVED,
    },
    {
        _id: "contact9",
        name: "Nguyen Van I",
        email: "nvi@example.com",
        phone: "0990123456",
        program: mockPrograms[8].title,
        message: "Tôi muốn biết về du học Singapore.",
        resolvedBy: mockUsers[8].name,
        resolvedAt: "2025-09-25",
        createdAt: "2025-09-20",
        updatedAt: "2025-09-25",
        status: EContactStatus.RESOLVED,
    },
    {
        _id: "contact10",
        name: "Phan Thi J",
        email: "ptj@example.com",
        phone: "0911234567",
        program: mockPrograms[9].title,
        message: "Tôi muốn hỏi về chương trình Thụy Sĩ.",
        resolvedBy: mockUsers[9].name,
        resolvedAt: "2025-10-30",
        createdAt: "2025-10-25",
        updatedAt: "2025-10-30",
        status: EContactStatus.RESOLVED,
    },
];

// FAQ mock data
export const mockFaqs: IFAQ[] = [
    {
        _id: "faq1",
        question: "Điều kiện du học Úc là gì?",
        answer: "Cần IELTS 6.0 và tốt nghiệp THPT.",
        category: "Úc",
        status: EStatus.ACTIVE,
    },
    {
        _id: "faq2",
        question: "Học phí du học Canada bao nhiêu?",
        answer: "Khoảng 625,000,000 VND/năm.",
        category: "Canada",
        status: EStatus.ACTIVE,
    },
    {
        _id: "faq3",
        question: "Du học Đức có miễn học phí không?",
        answer: "Có, nhiều trường miễn học phí.",
        category: "Đức",
        status: EStatus.ACTIVE,
    },
    {
        _id: "faq4",
        question: "Cần chứng chỉ gì để du học Nhật Bản?",
        answer: "Cần N3 tiếng Nhật.",
        category: "Nhật Bản",
        status: EStatus.ACTIVE,
    },
    {
        _id: "faq5",
        question: "Cơ hội việc làm sau du học Hàn Quốc?",
        answer: "Nhiều cơ hội việc làm và định cư.",
        category: "Hàn Quốc",
        status: EStatus.ACTIVE,
    },
    {
        _id: "faq6",
        question: "Du học Đài Loan cần chứng chỉ gì?",
        answer: "Cần TOCFL 3.",
        category: "Đài Loan",
        status: EStatus.ACTIVE,
    },
    {
        _id: "faq7",
        question: "Du học Mỹ cần chuẩn bị gì?",
        answer: "Cần SAT và tốt nghiệp THPT.",
        category: "Mỹ",
        status: EStatus.ACTIVE,
    },
    {
        _id: "faq8",
        question: "Học phí du học Pháp bao nhiêu?",
        answer: "Khoảng 550,000,000 VND/năm.",
        category: "Pháp",
        status: EStatus.ACTIVE,
    },
    {
        _id: "faq9",
        question: "Du học Singapore cần IELTS bao nhiêu?",
        answer: "Cần IELTS 6.0.",
        category: "Singapore",
        status: EStatus.ACTIVE,
    },
    {
        _id: "faq10",
        question: "Du học Thụy Sĩ cần chứng chỉ gì?",
        answer: "Cần B2 tiếng Anh.",
        category: "Thụy Sĩ",
        status: EStatus.ACTIVE,
    },
];

export const mockStats = {
    totalVisitors: 12543,
    uniqueVisitors: 8742,
    pageViews: 45892,
    avgSessionDuration: "3m 42s",
    bounceRate: "32.4%",
    topPages: [
        { name: "Homepage", views: 12450 },
        { name: "Programs", views: 8765 },
        { name: "Jobs", views: 6543 },
        { name: "Contact", views: 4321 },
        { name: "FAQ", views: 3210 },
    ],
    recentActivity: [
        { _id: 1, action: "New user registered", time: "2 min ago" },
        { _id: 2, action: "Job application submitted", time: "15 min ago" },
        { _id: 3, action: "Contact form submitted", time: "1 hour ago" },
        { _id: 4, action: "New blog post published", time: "3 hours ago" },
    ],
};